### ISSUE TITLE
Website Redesign breaks calendar scraping

### ISSUE THREAD

**Issue by willgraf** [Munfred/gcaltech.com#2]
Looks like the calendar website was updated, causing the service to break.

[Here's the new link for the site](https://www.caltech.edu/campus-life-events/master-calendar)

I'm not sure if the HTML parsing will still work.  If it is broken due to the redesign as well, I would be happy to help re-scrape the site (I'll probably convert to [scrapy](https://github.com/scrapy/scrapy) or requests + lxml)

**Comment by Munfred** [comment]
Thanks! I'm on a trip right now but I'll see if cjanging the link works as soon as I get a chance and I'll let you know if changes to the scraper are neeelded

**Comment by Munfred** [comment]
Ok, confirmed, just changing the link won't do it, they made several changes to the HTML.  I won't have time to work on this for another 10 days, so if before then you write a scrapper and email composer that works with the current master calendar website I'm happy to put it up.

**Comment by Munfred** [comment]
Oh hey we fixed this months ago yay!
